ARG JAVA_VERSION

FROM bellsoft/liberica-runtime-container:jdk-${JAVA_VERSION}-glibc

LABEL org.opencontainers.image.source=https://github.com/Dimantchick/Spring-docker-container
LABEL org.opencontainers.image.description="Base docker image for Spring boot containers. \
                                           Based on bellsoft/liberica-runtime-container image. \
                                           With fontconfig support \
                                           Running container with javauser (non root)."

RUN apk add --update --no-cache fontconfig ttf-dejavu curl jq && \
    rm -rf /var/cache/* && \
    fc-cache -f && \
    rm -rf /var/lib/apk/* && \
    rm -f /sbin/apk && \
    rm -rf /etc/apk && \
    rm -rf /lib/apk && \
    rm -rf /usr/share/apk && \
    rm -rf /var/lib/apk

# Application user
RUN addgroup -S java && adduser -S javauser -G java \
    mkdir /home/javauser/.fonts && chown -R javauser:java /home/javauser/.fonts && \
    chown -R 1000:1000 /usr/share/fonts && \
    mkdir /workspace && chown -R javauser:java /workspace && \
    mkdir /workspace/logs && chown -R javauser:java /workspace/logs

WORKDIR /workspace

# Run as root - bad practice
USER javauser

# Spring Boot Launcher
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]